name: build-ffmpeg-static

on:
  workflow_dispatch:

jobs:
 build-cuda-ubuntu-docker:
    name: build in ubuntu docker with cuda
    strategy:
      matrix:
        os: ['18.04']
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: build ffmpeg
        run: |
          bash ffmpeg-nvenc-build.sh
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg
          path: artifacts/*
